### ISSUE TITLE
Various Issues upon mass Transporting Identified

### ISSUE THREAD

**Issue by PizzaTimeJoshua** [GearsProgress/Poke_Transporter_GB#16]
Spent a few hours doing this manually as intended. From Gen 1 -> Gen 3 -> Gen 4
This was done from English Yellow to English Leaf Green Transferred then to English Heart Gold.
The Leaf Green Save did have other Mystery Gift events active prior to transportation.

I've attached all the save files below.
[GB Transported Saves.zip](https://github.com/user-attachments/files/17001306/GB.Transported.Saves.zip)
Note: Some Pokemon have HMs requiring you to delete them via Move Deleter. I forgot to do this in the Leaf Green Save File so you may need to delete them if you plan on replicating this transport from Gen 3 -> Gen 4

Issues Observed:

1. Pokemon May Transfer with a Blank Nickname (e.g. Bulbasaur)
2. Pokemon May be unable to be transported from Gen 1 to Gen 3 at the initial attempt
3. Pokemon May Transfer with with extra characters in Nickname (e.g. Butterfree)
4. Pokemon May Transfer with empty Original Trainer Name (e.g. Pidgeot)
5. Pokemon May Transfer with an extra Space in front of the Original Trainer Name (e.g Pidgey)
6. Pokemon May Transfer with an extra Character in front of the Original Trainer Name (e.g Charmeleon)
7. Pokemon May have Invalid Encounter Type after Transferred to Gen 4 (e.g. Rhydon)
8. Pokemon May have PID + Correlation not match for the Encounter Type after Transfer to Gen 4
9.  Safari Zone Encounter Pokemon does not have correct Pokeball Type (e.g. Kangaskhan, Exeggcute)

Issues 1-6 appeared appears prominently in the first batch of Pokemon I attempted to send. Afterwards, its occurrence was much less. This issued seemed to occur at the final 20 Pokemon, but after cancelling the transfer and trying again the issue disappeared. This didn't seem to be the case for the first 20 Pokemon transferred.
The Pokemon left behind due to being unable to transfer _at the first attempt_ are still in the post-transferred Yellow Save File.

Issue 4 occurs in NPC traded Pokemon like Jynx and Farfetch'd where the rest of the Pokemon in the Box didn't have this issue.
Issue 9 does not have all Pokemon from Safari Zone labeled as Safari encounters, some of them may be have egg like Dratini so they avoid this issue.

Some Pokemon are completely legal, some have very apparent legality issues, and other have nuanced legality issues (incorrect Encounter Type)

My suggestion is to have all breedable Pokemon have Egg Encounter type to solve the Encounter Type (assuming you follow the proper egg generation) to normalize the Encounter Types, potentially making Issues 8-9 easier to solve. This would also solve the Safari Ball issue since all Pokemon bred in Gen 3 have Pokeball by default.

**Comment by GearsProgress** [comment]
Hi there!! Sorry for the late response, but I believe most the issues you encountered were caused by a bug I just found the fix to! I pushed a release yet, but the details can be found at the end of this issue thread:

https://github.com/GearsProgress/Poke_Transporter_GB/issues/9

Thank you for providing your save files as well! As such, I was able to confirm my theory by finding that your Pidgeot has a Special EV of 2302, which becomes 0x08FE in hex (with 0xFE being the problem byte). Obviously not your fault, but it backs up the theory that your issues should be solved with the upcoming bug fix!

As far as the Safari Ball part goes- I am definitely planning on changing that in the near future as well. My goal is to get the translation work done first, but it will be changed sometime soon as well!!
