### ISSUE TITLE
Full Emulation, Language, and Link Cable Support

### ISSUE THREAD

**Issue by SilverTheShinyEevee** [GearsProgress/Poke_Transporter_GB#21]
Hi, I saw a [GitHub issue](https://github.com/GearsProgress/Poke_Transporter_GB/issues/1) about emulation support, but I have a threefold followup question. When will multi-language support (not just other non-English games, but a multi-language version of Poké Transporter GB itself) be available? Also, would it be possible to enable emulation with just a mod for a GBA emulator? If I wanted to do this, my [app](https://apps4flip.nyc3.cdn.digitaloceanspaces.com/myboy.apk) is unable to be updated, as the [host site](https://apps4flip.com/apps) is basically dead. Also, when will a GBA Link Cable be supported for the transporter?

**Comment by GearsProgress** [comment]
Hi there!! To answer your questions-
1. The exact timeframe for the multi-language support is unfortunately still up in the air. It's currently in development, but I haven't had as much time to work on the project as I would have wished. But it is coming!!
2. Emulation is tricky, because while the connection is able to be emulated correctly, I haven't been able to find an emulator that supports GBC link cables specifically. Using a modified emulator is theoretically possible, but I've currently been focusing on fixing bugs instead of modding an emulator.
3. Unfortunately, a regular GBA cable will never be supported due to how the two cables are wired. There is theoretically a way to do it with two GBA cables, but I haven't had the chance to fully look into that

**Comment by Antviau** [comment]
If you need a beta tester for the french version Pokemon games I'm up for it
