### ISSUE TITLE
Correct met level, wrong actual level

### ISSUE THREAD

**Issue by AWildOreo** [GearsProgress/Poke_Transporter_GB#26]
I just transferred a few pokemon from Red to LeafGreen and I noticed that they had the correct met level, but the wrong actual level. The only pokemon that had its correct level was the first one (a lv 25 Kangaskhan). Every other one was either level 15 or 18, not including a stabilized Mew I also had. I'm typing this on my phone so give me a minute to send the save file. The nicknames in the pictures sent are supposed to be backwards so ignore them.
![4892eacb-63b0-43d3-bb0d-400b85d7996d](https://github.com/user-attachments/assets/496ea5ce-6cd6-49c7-bfe3-f45eabe45295)
![8ce83c33-c351-44d3-834d-2549b33cceed](https://github.com/user-attachments/assets/e5d47729-1a77-44a3-944c-3adc4cf914c2)
![17326785852845421706384786899283](https://github.com/user-attachments/assets/d99380e2-e3c8-41f3-ad39-568d0232d4b4)

On an unrelated note, is sending glitch pokemon or pokemon above lv 100 supported because I have some in a few boxes.

**Comment by AWildOreo** [comment]
The save should be on the correct box (361-390 [Box 13]). Ignore the other boxes. I looked for a moment on pkhex but I wouldn't even begin to know what I'm looking for to figure out why this happened.

[POKEMON LEAF [BPGE01].zip](https://github.com/user-attachments/files/17928795/POKEMON.LEAF.BPGE01.zip)

I have no way to back up regular game boy games so I wouldn't be able to show you how they originally were.

**Comment by GearsProgress** [comment]
That's... really interesting. The EXP data is right in the middle of the data structure, so there shouldn't be any issue of dropped data. I'll take a look into what could've gone wrong- it's also really weird that it's specifically level 15 or 18, and that Kangaskhan was correct.

I'll keep you updated- so sorry that you had issues! If you'd like me to, I can send you back a fixed version of the save file with the correct levels!

**Comment by AWildOreo** [comment]
If it means anything, I was using a 3rd party cord and attempted to use the transfer 3 times on an original game boy before I switched to sp and it worked.
It shouldn't, considering every time it failed nothing was corrupted.
As for correcting the levels, I think it's funny having them at that level. If I really wanted to I could just boost their levels in pkhex, unless that messes with transferring.

**Comment by AWildOreo** [comment]
Not gonna lie I rushed the transfer. I wasn't paying attention because I was happy that I actually got the transfer to work in general and also my sp was on red (I had a second one charging). I can make another transfer to see if it happens again, one with a mew and one without, just to see if that may be a thing.

**Comment by GearsProgress** [comment]
You're all good!! I ran my test save file through a transfer and all the Pokémon were level 15 or 18- clearly something got messed up on my end with the code... whoops! I'm really glad you caught that haha

**Comment by Twispan** [comment]
Adding onto this issue. When I tried transferring from my copy of Crystal to Emerald (both English copies), all but the first slot of my party was either level 15 and 18 with their met levels being as they should've. However I've also observed in PKHeX when trying to correct them that they did not even have games of origin listed, somehow. This is strange, because recently I've done another transfer with my copy of Blue and the end result was perfectly normal, and it even had it's "game of origin"? (Third image, the Mankey)
![Strange](https://github.com/user-attachments/assets/2a565e2a-0a8d-41f3-b02c-db06929180d8)
![level 18](https://github.com/user-attachments/assets/7bbbdf0a-f6cf-4dc5-9984-e4aed5f90c23)
![Blue](https://github.com/user-attachments/assets/bc6b95be-9cc3-4d1b-9b7d-218bf1f8a06d)

**Comment by Twispan** [comment]
OH! I just noticed something else that I'm unsure of. Somehow, most of the other Pokemon I've transferred were listed as being "from" Heartgold in PKHeX. Is this supposed to be correct?
![image](https://github.com/user-attachments/assets/039782f4-e321-4222-b552-ce6558c5e430)

**Comment by GearsProgress** [comment]
Thanks for the extra info! It definitely seems like the conversion data is getting messed up somewhere- I'll take a look at it later today and hopefully have a solution soon!

**Comment by Twispan** [comment]
It seems that the incorrect level bug is still present, somehow?? I just did four test transfers (same games, English Emerald and English Crystal) after updating my cartridge to the latest version of Poke Transporter GB and every single time it's ended up with the same result, first Pokemon in the PC being at a normal level and everything else at level 15/18, along with the other issue of no game of origin when checking in PKHeX (Was that addressed in the latest version? I don't know). Strange how the bug continues to persist even after fixing it, I'm almost certain I've updated my hardware correctly to the latest version. Is this just a me thing on the update, or is this still happening for others?

![image](https://github.com/user-attachments/assets/d2ac4bbc-e932-46d7-8da6-ae55987cc6f9)


https://github.com/user-attachments/assets/1994b999-7935-46ae-99a3-ca02d01e97c7


https://github.com/user-attachments/assets/80d17749-8889-4413-acd8-466dbc974a04

**Comment by GearsProgress** [comment]
I'm so sorry that this is still an issue- I definitely ran some tests on my end, but clearly that wasn't enough 😅. Do you happen to still have your save file that the issue was happening with? I'd love to be able to use exactly what you have in order to -for sure this time- fix this bug

**Comment by Twispan** [comment]
Yes of course! Would you prefer before or after the transfer?

**Comment by GearsProgress** [comment]
Yes, having the save file before the transfer as well would be perfect!!

**Comment by Twispan** [comment]
Alright! Let me get that for you real quick. This one's an auto-backup from a few days ago when I last touched the file.
[Before Transfer.zip](https://github.com/user-attachments/files/18142145/Before.Transfer.zip)

**Comment by GearsProgress** [comment]
Awesome- Do you happen to have the GameBoy save file before the transfer as well? Sorry for all the requests haha 😅

**Comment by Twispan** [comment]
Yup! Don't worry about the requests by the way, It's just part of the process of figuring this out.
[Crystal Transfer.zip](https://github.com/user-attachments/files/18142179/Crystal.Transfer.zip)

**Comment by GearsProgress** [comment]
Perfect!! This is exactly what I need to truly squash this bug- thank you *so* much!!

**Comment by GearsProgress** [comment]
Alrighty- good news, good news, and bad news. Good news is that I figured out what the bug is and what's causing it. Bad news is that it's something that's pretty baked in, and I'm going to need to rewrite the conversion process in order to fix it. Good news about that though is that it'll end up being a lot more optimized and is really something I've been meaning to do for a while... it'll just take a bit to fully fix.

**Comment by GearsProgress** [comment]
Good news! That was a bit easier to fix than expected! The most recent release should work now.

Also! The missing met game is just because PKHeX doesn't like having a Gen 3 Pokemon with a Gen 4 game as the met location- it'll be fine once it gets sent to Gen 4! Figured that out while debugging today 🙃
