### ISSUE TITLE
Emulator 

### ISSUE THREAD

**Issue by alwaysdimdim** [GearsProgress/Poke_Transporter_GB#3]
Does it works in emulator android? like myboy...

**Comment by GearsProgress** [comment]
Emulator support is tricky at the moment due to a lack of emulator support for specifying which Link Cable the player is using. There is an issue open about emulator support, so I'm going to close this one as a duplicate and keep the updates there :)

https://github.com/GearsProgress/Poke_Transporter_GB/issues/1
